// <auto-generated />
using System;
using EdgarAparicio.PastelesYummy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EdgarAparicio.PastelesYummy.Data.Migrations
{
    [DbContext(typeof(DbContextPasteleriaYummy))]
    partial class DbContextPasteleriaYummyModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EdgarAparicio.PastelesYummy.Business.Entity.ArticuloCarritoCompras", b =>
                {
                    b.Property<int>("ArticuloCarritoComprasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CarritoComprasId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PastelId")
                        .HasColumnType("int");

                    b.HasKey("ArticuloCarritoComprasId");

                    b.HasIndex("PastelId");

                    b.ToTable("ArticulosCarritoCompras");
                });

            modelBuilder.Entity("EdgarAparicio.PastelesYummy.Business.Entity.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoriaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            CategoriaNombre = "Pastel de Frutas"
                        },
                        new
                        {
                            CategoriaId = 2,
                            CategoriaNombre = "Pastel de Quesos"
                        },
                        new
                        {
                            CategoriaId = 3,
                            CategoriaNombre = "Pastel de Temporada"
                        });
                });

            modelBuilder.Entity("EdgarAparicio.PastelesYummy.Business.Entity.DetallePedido", b =>
                {
                    b.Property<int>("DetallePedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PastelId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DetallePedidoId");

                    b.HasIndex("PastelId");

                    b.HasIndex("PedidoId");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("EdgarAparicio.PastelesYummy.Business.Entity.Pastel", b =>
                {
                    b.Property<int>("PastelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCorta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionLarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnStock")
                        .HasColumnType("bit");

                    b.Property<string>("ImagenThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacionAllergy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PastelSemana")
                        .HasColumnType("bit");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PastelId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Pasteles");

                    b.HasData(
                        new
                        {
                            PastelId = 1,
                            CategoriaId = 1,
                            DescripcionCorta = "¡Nuestras famosos pasteles de manzana!",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = true,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de Manzana",
                            PastelSemana = true,
                            Precio = 129.5m
                        },
                        new
                        {
                            PastelId = 2,
                            CategoriaId = 2,
                            DescripcionCorta = "¡Te encantará!",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = true,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecakesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecake.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de Queso con Arandanos",
                            PastelSemana = false,
                            Precio = 189.5m
                        },
                        new
                        {
                            PastelId = 3,
                            CategoriaId = 2,
                            DescripcionCorta = "Pastel de queso simple. Duro Placer!",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = true,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecakesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecake.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de Queso",
                            PastelSemana = false,
                            Precio = 189.5m
                        },
                        new
                        {
                            PastelId = 4,
                            CategoriaId = 1,
                            DescripcionCorta = "Un clasico de verano!",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = true,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypiesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypie.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de Cerezas",
                            PastelSemana = false,
                            Precio = 159.5m
                        },
                        new
                        {
                            PastelId = 5,
                            CategoriaId = 3,
                            DescripcionCorta = "Felices vacaciones con este pastel",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = true,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepiesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepie.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de manzna de navidad",
                            PastelSemana = false,
                            Precio = 139.5m
                        },
                        new
                        {
                            PastelId = 6,
                            CategoriaId = 3,
                            DescripcionCorta = "Una navidad favorita",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = true,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypiesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypie.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de arandano",
                            PastelSemana = false,
                            Precio = 179.5m
                        },
                        new
                        {
                            PastelId = 7,
                            CategoriaId = 1,
                            DescripcionCorta = "Dulce como un Durazno",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = false,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpiesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpie.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de durazno",
                            PastelSemana = false,
                            Precio = 159.5m
                        },
                        new
                        {
                            PastelId = 8,
                            CategoriaId = 3,
                            DescripcionCorta = "Nuestro hallowen favorito",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = true,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpiesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpie.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de calabaza",
                            PastelSemana = true,
                            Precio = 129.5m
                        },
                        new
                        {
                            PastelId = 9,
                            CategoriaId = 1,
                            DescripcionCorta = "Increible, demasiado dulce",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = true,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpiesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpie.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de Riubarbo",
                            PastelSemana = true,
                            Precio = 159.5m
                        },
                        new
                        {
                            PastelId = 10,
                            CategoriaId = 1,
                            DescripcionCorta = "Nuestro delicioso pastel de fresa",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = true,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypiesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypie.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de Fresa",
                            PastelSemana = false,
                            Precio = 159.5m
                        },
                        new
                        {
                            PastelId = 11,
                            CategoriaId = 2,
                            DescripcionCorta = "Te encantara",
                            DescripcionLarga = "Glaseado de tarta de queso con gelatina de zanahoria. Rollo dulce mazapán malvavisco toffee brownie brownie caramelo tootsie roll. Pastel de chocolate, pan de jengibre, tootsie, pastel de avena, pastel, barra de chocolate, galleta, dragée, brownie. Lollipop pastel de avena de garra de oso de pastel de algodón de azúcar. Tarta de postre con bastones de caramelo Dragée. Mazapán dragée gomitas piruletas azufaifa barra de chocolate bastones de caramelo. Glaseado de pan de jengibre chupa chups galleta de algodón de azúcar gomitas de bombón glaseado dulce. Pastel de chocolate danés de galleta de brownie de piruleta de gomitas. Tarta danesa de donut de chocolate con macarrones y galletas en polvo. Pastel de zanahoria croissant grageas gotas de limón regaliz gotas de limón galleta piruleta toffee. Pastel de zanahoria pastel de zanahoria regaliz azúcar ciruela topping pastel de bombones muffin azufaifa. Caramelos de tarta de oblea de pastelería gelatina garra de oso. Tarta de tarta de tiramisú con gotas de limón danés. Gomitas de bizcocho de brownie dragée.",
                            EnStock = false,
                            ImagenThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecakesmall.jpg",
                            ImagenUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecake.jpg",
                            InformacionAllergy = "",
                            Nombre = "Pastel de Fresas con Queso",
                            PastelSemana = false,
                            Precio = 189.5m
                        });
                });

            modelBuilder.Entity("EdgarAparicio.PastelesYummy.Business.Entity.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Direccion1")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Direccion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("PedidoEntregado")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PedidoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("EdgarAparicio.PastelesYummy.Business.Entity.ArticuloCarritoCompras", b =>
                {
                    b.HasOne("EdgarAparicio.PastelesYummy.Business.Entity.Pastel", "Pastel")
                        .WithMany()
                        .HasForeignKey("PastelId");
                });

            modelBuilder.Entity("EdgarAparicio.PastelesYummy.Business.Entity.DetallePedido", b =>
                {
                    b.HasOne("EdgarAparicio.PastelesYummy.Business.Entity.Pastel", "Pastel")
                        .WithMany()
                        .HasForeignKey("PastelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EdgarAparicio.PastelesYummy.Business.Entity.Pedido", "Pedido")
                        .WithMany("DetallePedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdgarAparicio.PastelesYummy.Business.Entity.Pastel", b =>
                {
                    b.HasOne("EdgarAparicio.PastelesYummy.Business.Entity.Categoria", "Categoria")
                        .WithMany("Pasteles")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
